# Selección del lenguaje: C++
language: cpp

# Seleeción de compiladores
compiler:
  - gcc

#Instalacíón 
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq lcov curl build-essential

#install:
#  - sudo apt-get update && sudo apt-get install -y \
#    build-essential \
#    python \
#    git \


before_script:
  - mkdir build

script: 
  - cd build
  - cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - make coveralls
