# Selección del lenguaje: C++
language: cpp

# Seleeción de compiladores
compiler:
  - gcc

#Instalacíón 
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq lcov curl build-essential python git cmake wget unzip valgrind tree
  - sudo apt-get install -y -qq libsnappy-dev zlib1g-dev libbz2-dev
#libgflags-dev

#install:
#  - sudo apt-get update && sudo apt-get install -y \
#    build-essential \
#    python \
#    git \


before_script:
  - mkdir build
  - tree -L 2 -d

script: 
  - cd build
  - tree -L 2 -d
  - cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - make coveralls
